version: '3'
services:
  # youapp:
  #   container_name: youapp_api
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   volumes:
  #     - ./src:/app/src
  #   env_file: ./.env
  #   ports:
  #     - '4003:4003'
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - youapp

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodata:/var/lib/mongo/data:rw
    networks:
      - youapp
  
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - 8075:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    volumes:
      - mongoexpress:/var/lib/mongoexpress/data:rw
    depends_on:
      - mongodb
    networks:
      - youapp


  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redisdata:/bitnami/redis/data:rw
    ports:
      - 6379:6379
    networks:
      - youapp

networks: 
    youapp:
        driver: bridge

volumes:
  mongodata:
    driver: local
  redisdata:
    driver: local
  mongoexpress:
    driver: local